version: '2'
services:
    cartracker3-app:
        image: cartracker3
        external_links:
            - cartracker3-postgresql:postgresql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/cartracker3
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    cartracker3-postgresql:
        extends:
            file: postgresql.yml
            service: cartracker3-postgresql
