version: '2'
services:
    cartracker3-postgresql:
        container_name: cartracker3-postgresql
        image: postgres:9.5.4
        # volumes:
        #     - ~/volumes/jhipster/cartracker3/postgresql/:/var/lib/postgresql/
        environment:
            - POSTGRES_USER=cartracker3
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
